In [2]:
import duckdb
import polars as pl
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter

con = duckdb.connect("../data/m5.db")

In [3]:
con.execute("SHOW TABLES").fetchdf()

                     name
0                calendar
1             dataset_raw
2  sales_train_evaluation
3  sales_train_validation
4       sample_submission
5             sell_prices

In [8]:
df = con.execute("SELECT * FROM dataset_raw LIMIT 5").fetchdf()

df

,series_id,state_id,store_id,cat_id,dept_id,item_id,date,sell_price,sales,mnt_gross_sales,snap,event_name,event_type
0,FOODS_1_001_CA_1,CA,CA_1,FOODS,FOODS_1,FOODS_1_001,2011-01-29,2.0,3,6.0,0,None,None
1,FOODS_1_001_CA_1,CA,CA_1,FOODS,FOODS_1,FOODS_1_001,2011-01-30,2.0,0,0.0,0,None,None
2,FOODS_1_001_CA_1,CA,CA_1,FOODS,FOODS_1,FOODS_1_001,2011-01-31,2.0,0,0.0,0,None,None
3,FOODS_1_001_CA_1,CA,CA_1,FOODS,FOODS_1,FOODS_1_001,2011-02-01,2.0,1,2.0,1,None,None
4,FOODS_1_001_CA_1,CA,CA_1,FOODS,FOODS_1,FOODS_1_001,2011-02-02,2.0,4,8.0,1,None,None

In [ ]:
df = con.execute("SELECT * FROM sell_prices LIMIT 5").fetchdf()

df

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [ ]:
df = con.execute("SELECT * FROM calendar ORDER BY date").fetchdf()

df

In [ ]:
df = con.execute("SELECT * FROM sales_train_evaluation LIMIT 5").fetchdf()

df

In [4]:
df = con.execute("SELECT d, sum(sales) as total_sales FROM sales_train_validation GROUP BY d ORDER BY d").fetchdf()

df['d_num'] = df['d'].str.extract(r'(\d+)').astype(int)
df = df.sort_values('d_num').reset_index(drop=True)

df

           d  total_sales  d_num
0        d_1      32631.0      1
1        d_2      31749.0      2
2        d_3      23783.0      3
3        d_4      25412.0      4
4        d_5      19146.0      5
...      ...          ...    ...
1908  d_1909      35343.0   1909
1909  d_1910      35033.0   1910
1910  d_1911      40517.0   1911
1911  d_1912      48962.0   1912
1912  d_1913      49795.0   1913

[1913 rows x 3 columns]

In [5]:
df = con.execute("SELECT d, sum(sales) as total_sales FROM sales_train_evaluation GROUP BY d ORDER BY d").fetchdf()

df['d_num'] = df['d'].str.extract(r'(\d+)').astype(int)
df = df.sort_values('d_num').reset_index(drop=True)

df

           d  total_sales  d_num
0        d_1      32631.0      1
1        d_2      31749.0      2
2        d_3      23783.0      3
3        d_4      25412.0      4
4        d_5      19146.0      5
...      ...          ...    ...
1936  d_1937      37096.0   1937
1937  d_1938      36963.0   1938
1938  d_1939      42552.0   1939
1939  d_1940      51518.0   1940
1940  d_1941      54338.0   1941

[1941 rows x 3 columns]